### ISSUE TITLE
Bug: Sorting ratings by most liked does not work

### ISSUE THREAD

**Issue by StefanieKrohmann** [The-Agile-Avengers/icu-connect-backend#110]

**Comment by solodezaldivar** [comment]
@msalze can you have a look at this? 
![image](https://github.com/The-Agile-Avengers/icu-connect-backend/assets/55449626/7945e4e2-829d-43ff-8356-60b6de68c5c2)

I think line 136 does nothing as the Field "thumbsUp" is a Set and this alone cannot be used for sorting.
Also, I think the logic should be:
`Sort sort = Sort.by("creation").descending();`
`if (sortByMostLiked.isPresent() && sortByMostLiked.get()) {`
`            sort = Sort.by("thumbsUp").descending();`
 `}` 
 to accommodate the scenario where the optional boolean is not given at all
