### ISSUE TITLE
T11.1: Create GET endpoint to retrieve ratings for a course

### ISSUE THREAD

**Issue by msalze** [The-Agile-Avengers/icu-connect-backend#47]

**Comment by Taremeh** [comment]
Please include `username` in the response objects (i.e. a Rating/Review object should contain the username of the person who posted the review)

currently missing, as seen in this sample response:
<img width="794" alt="image" src="https://user-images.githubusercontent.com/1512652/230736388-796607ab-f7e7-4abc-ab43-74c48b2dd9d8.png">

**Comment by msalze** [comment]
In your example, the user has the field email, is this needed? I don't think that it should be available in the frontend, unless the actual user is querying it.
The avatar is currently not implemented in the backend. Will follow.
